function _todo_usage --description "Print todo command usage"
    echo "todo — manage ~/todo.md (override the path with \$TODO_FILE)"
    echo ""
    echo "Tasks live in three sections (## Doing / # Todo / ## Archive). Each task"
    echo "line is  '- [ ] <text> @<tag> (<id>)'  with optional indented context lines."
    echo ""
    echo "Commands:"
    echo "  todo add <text> [@tag]    Add a task to the backlog"
    echo "  todo edit <id> <text>     Replace a task's text (trailing @tag updates the tag)"
    echo "  todo note <id> <text>     Append an indented context line to a task"
    echo "  todo tag <id> <tag|->     Set, or clear (-), a task's @tag"
    echo "  todo show <id>            Print a task and its context"
    echo ""
    echo "Lifecycle (separate commands):"
    echo "  doing [<id>|<text>]       Promote a task to Doing, or add an interruption"
    echo "  done [<id>]               Mark a task done"
    echo "  next [n] [@tag]           Show Doing + next n backlog tasks (filter by @tag)"
    echo "  archive                   Move completed tasks to Archive"
end
